name: travellio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  get: ^4.6.6
  flutter_svg: ^2.0.7
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  lottie: ^2.6.0
  dot_navigation_bar: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_animation_progress_bar: ^2.3.1
  cloud_firestore: ^4.13.2
  google_nav_bar: ^5.0.6
  swipe_cards: ^2.0.0+1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/misc/
    - assets/design/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf 
        - asset: assets/fonts/Raleway-Bold.ttf 
        - asset: assets/fonts/Inter-Regular.ttf 
        - asset: assets/fonts/Inter-Bold.ttf 
